theme: jekyll-theme-merlot

google:
  analytics:
      id: UA-156621148

plugins:
 - jekyll-github-metadata
 - jekyll-feed
 - jekyll-gist
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-mentions
 - jekyll-coffeescript
 - jekyll-redirect-from
 - jekyll-sass-converter
 - jekyll-seo-tag
 - jekyll-archives
 - jekyll-jupyter-notebook
 - kramdown
 - liquid
 - rouge
 - pygments
 - jemoji
 - sass
 - safe_yaml
